### ISSUE TITLE
Constant time comparision isn't really constant time

### ISSUE THREAD

**Issue by pocesar** [defuse/password-hashing#46]
Didn't check the other implementions, but only PHP, it's checking:
```php
for($i = 0; $i < strlen($a) && $i < strlen($b); $i++) //...
```
When supplying a bigger password for $b (like 100000 in length), the function will stop at the length of $a, which is much smaller, which after sometime and persistence can actually discover the length of the pbkdf2 stored, defeating the purpose of a constant time comparision.

both values should be sha1-hashed and transformed to hex, then compared. they will always have the same length, thus avoiding the problem.

The implementation, IMHO, should be more like this https://github.com/pocesar/password-hashing/blob/true-constant-time/PasswordHash.js#L94-L111

**Comment by defuse** [comment]
This isn't a problem because the length of the PBKDF2 output is public knowledge (constant) and does not need to be secret. There is no advantage to keeping it secret. The password hashing is *not* a MAC function, so the correct hash should never be supplied by an attacker anyway.

However, if you look at the `validate_password()` function, it ensures both `$a` and `$b` have the same length.

**Comment by defuse** [comment]
By the way, SHA1ing the inputs before comparing doesn't actually solve the problem -- the time it takes to compute the SHA1 still varies depending on the length, but with less granularity. See also #11.

**Comment by pocesar** [comment]
makes sense :)
