### ISSUE TITLE
Implementation of a function "password_needs_rehash"?

### ISSUE THREAD

**Issue by module0x90** [defuse/password-hashing#74]
Hiya,

I was wondering whether it would be useful to have a "password_needs_rehash" for that case the parameters have changed.
An example is probably if you want to go from SHA1 to SHA256 and would like to have all password rehashed with SHA256. I am not playing on the deprecation of SHA1 here.
I just used your library to transition from a somwhat "$horrible_hash" to use yours, but going forward, it would be handy to be able to do that with your library as well.

Thanks anyway, keep up the good work. Also many thanks for your so very good explanation on your site.

Cheers

Thomas

**Comment by defuse** [comment]
That's a good idea!

**Comment by mythz** [comment]
Is there a reason why SHA1 should be preferred to SHA256? i.e. are there any downsides for using SHA256 instead?

**Comment by module0x90** [comment]
SHA1 is considered to be deprecated, please see
https://blog.qualys.com/ssllabs/2014/09/09/sha1-deprecation-what-you-need-to-know
https://shaaaaaaaaaaaaa.com/

I don't think so.

**Comment by defuse** [comment]
The only reason we use SHA1 in this library is because it's the only thing supported *natively* across all the platforms. If we wanted to use SHA256 here, I'd have to include a non-native implementation of it in a couple of the implementations, making them slower (relative to an attacker with an optimized SHA256) and therefore weaker. What matters for password hashing is that your implementation is just as fast as the attacker's, otherwise you're at a disadvantage because you're forced to use fewer iterations.

SHA1 certainly shouldn't be used anywhere you need collision resistance (e.g. as a MAC), but PBKDF2 and password hashing doesn't rely on collision resistance, just preimage resistance. We're a long way from seeing practical preimage attacks on SHA1. Currently, the best attack gives you SHA1 collisions in 2^60 operations (nearly practical), but the [best preimage attack](https://eprint.iacr.org/2012/440.pdf) is north of 2^150 operations (definitely not practical).

I would actually rather wait until all of these platforms support Argon2 or at least scrypt and then switch to that.

**Comment by module0x90** [comment]
Thanks for clarification.

Apologies for muddying the water.
My links are referring to using SHA1 in cryptography *only*.

**Comment by defuse** [comment]
No worries @module0x90! I want SHA1 to dies as soon as possible.

**Comment by defuse** [comment]
This code is being maintained only, I won't have time to add new features, so I'm going to close this issue. If I ever do revisit this and make compatible Argon2 implementations, I'll make sure it has this feature!
