### ISSUE TITLE
VerifyPassword with SlowEquals

### ISSUE THREAD

**Issue by puffosauro** [defuse/password-hashing#82]
This is not really an issue, but a question about the SlowEquals method for verify the password.
Why don't you use a simple byte-byte comparison?
There isn't a (unlikely) possibility of a false positive?

**Comment by defuse** [comment]
There's an *extremely* unlikely possibility of a false positive, but it can't happen in the lifetime of this universe. The reason it's done this way is because there's no way to guarantee an implementation of a byte-by-byte comparison within PHP is constant time. There's nothing preventing the PHP interpreter from being "too smart" and turning the constant-time algorithm into a variable-time one. The solution is to use HMAC with a random key to do a comparison, since that will be constant-time as long as the implementation of HMAC is.
