### ISSUE TITLE
SHA256 support for Java 8

### ISSUE THREAD

**Issue by dmitrymurashenkov** [defuse/password-hashing#89]
Java 8 now supports PBKDF2WithHmacSHA256, perhaps it would be nice to add support for it.

https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html

**Comment by defuse** [comment]
I'm going to leave things as-is because (A) even though there are practical collision attacks on SHA1, it's still safe for how it's being used in this library, (B) in order to keep compatibility between all the languages SHA256 would have to be be available in all of them and incompatible implementations/settings would lead to confusion, and (C) people should really be migrating away from PBKDF2 to the best of scrypt, yescrypt, Argon2, etc. that's available to them.

Once one of the PHC finalists is available natively in all of the languages we currently support, I'll put out a new version this library supporting it.
